Adds Channel Details Loading Screen
ethereum-push-notification-service/epns-dapp-dev pull request #118
Opened 2022-08-16 11:38 UTC by madhurg-epns

2022-08-19 11:29 UTC, nilesh46 requested changes
Resolve the alignments
Actual behavior: 
![image](https://user-images.githubusercontent.com/54444545/185608940-1dc6008a-1fcb-4b0c-b9e4-354d33a51328.png)

Expected behavior: 
![image](https://user-images.githubusercontent.com/54444545/185609026-a41c812d-e397-4665-b600-14b21773fcb3.png)

2022-08-19 12:21 UTC, nilesh46 approved these changes
Great work!

2022-08-22 12:14 UTC, corlard3y approved these changes

2022-08-23 10:47 UTC, madhurg-epns commented
@nilesh46 I have added conditional font color on channel loading page to adjust for dark mode to this PR.

2022-08-26 20:07 UTC, closed without merging